### ISSUE TITLE
need help!

### ISSUE THREAD

**Issue by namjoub** [edm1/Credible-set-analysis#1]
hi there: i have snptest output and I am getting this error:
 C:\Users\Desktop\Credible-set-analysis-master\Credible-set-analysis-maste
 r> python.exe credible_set_analysis.py --i 8rsb.txt --o test --col bayesian_add_
 log10_bf
 Traceback (most recent call last):
 File "credible_set_analysis.py", line 68, in 
 main()
 File "credible_set_analysis.py", line 23, in main
 post_sum = reduce(sum_log10, list(df[args.col]))
 NameError: name 'reduce' is not defined

**Comment by edm1** [comment]
Hi @namjoub,

I believe you are getting this error because reduce has been moved to the functools module in python 3.

You could getting around this by using python 2. Alternatively adding `from functools import reduce` to the top of the script with the other import statements might work.

**Comment by namjoub** [comment]
thank you...the second option works...
best
